### ISSUE TITLE
Add options to translate ticket's messages

### ISSUE THREAD

**Issue by Camelik** [BlueTree242/DiscordSRVUtils#10]
Add options to translate ticket's messages

**Comment by BlueTree242** [comment]
> _No description provided._

You have to put a description. Even if title explains it.

**Comment by BlueTree242** [comment]
> Add options to translate ticket's messages 

Thanks for your suggestion. I am going to add it to the config and you can translate them yourself.

**Comment by BlueTree242** [comment]
I was adding it to the next version, but I made a mistake and had no time to fix, so I can't add it in the next version. But I promise it will be added in the SNAPSHOT 9.

**Comment by louanbastos** [comment]
Please bring this update to the stable version

**Comment by BlueTree242** [comment]
> Please bring this update to the stable version

The next update will contain it, also custom messages that can be embed

**Comment by BlueTree242** [comment]
Finally added in our 1.2.0-BETA-2
