### ISSUE TITLE
Litebans integration for DiscordSRVUtils

### ISSUE THREAD

**Issue by NotAShelf** [BlueTree242/DiscordSRVUtils#13]
As Litebans is a commonly used punishment plugin, I think an integration between DiscordSRVUtils and Litebans would be beneficial for the plugin.

The API can be found [here](https://gitlab.com/ruany/LiteBansAPI/-/wikis/home)

**Comment by BlueTree242** [comment]
Nice. Going to add it. But everyone will have to reset their config.

**Comment by BlueTree242** [comment]
Sadly, i can't test it after done, if anyone have a copy feel free to give me a copy so i can test. Dms open  join  https://discord.gg/MMMQHA4

**Comment by NotAShelf** [comment]
i do have a copy, but as per the plugin's TOS i'm not allowed to share the  jar under to circumstances

if there is another way i can test it on my own machine, i'd be happy to do so

**Comment by BlueTree242** [comment]
Someone already gave me the jar. Thanks to him

**Comment by Creeperz653** [comment]
um anyupdates

**Comment by NotAShelf** [comment]
> um anyupdates

according to the author on [spigotmc resource page](https://www.spigotmc.org/resources/discordsrvutils.85958/), this plugin was discontinued. I don't think we'll be getting said feature anytime

**Comment by BlueTree242** [comment]
> > um anyupdates
> 
> according to the author on [spigotmc resource page](https://www.spigotmc.org/resources/discordsrvutils.85958/), this plugin was discontinued. I don't think we'll be getting said feature anytime

Yes but new plugin is releasing with same features and more, if i dont add this in new plugin u can still open issue on new plugin when available

**Comment by BlueTree242** [comment]
Added
