### ISSUE TITLE
[Feature Request] Punishment Integration - Sender

### ISSUE THREAD

**Issue by kainlighty** [BlueTree242/DiscordSRVUtils#150]
Add unpunishment.operator. Because it is not visible who has unban the player, the wine is only the one who banned him earlier.

unban.json / unmute.json.

I'm using litebans.

**Comment by BlueTree242** [comment]
Added as `[punishment.revoker]` in [development builds](https://ci.bluetree242.dev/job/DiscordSRVUtils/)

Only Litebans support this feature

**Comment by kainlighty** [comment]
Thank you for your quick response. 
Do you install the string 'Permanent' in the code, or is the plugin itself responsible for this?

I didn't find this in the "litebans" configurations. If you have installed this, add this state to the "messages" so that I can translate/change it for myself

**Comment by BlueTree242** [comment]
Use this to change Permanent to your own word

`${#punishment.reason.equals(\"Permanent\") ? \"YOUR OWN WORD HERE\" : #punishment.reason}`

**Comment by kainlighty** [comment]
It's very good that this is thought out. Thanks (:
