### ISSUE TITLE
[BUG] Tickets created by the bot do not inherit category permissions.

### ISSUE THREAD

**Issue by ghost** [BlueTree242/DiscordSRVUtils#155]
**Describe the bug**
If you have a category with certain permissions set up, the bot does not inherit them into the ticket channels on creation.

**To Reproduce**
1. Setup categories with permissions.
2. Setup DiscordSRVUtils ticket feature.
3. Ask a member to create a ticket.

**Expected behavior**
Ticket Channels should inherit category permissions.

**Screenshots**
![image](https://github.com/BlueDevelopersInc/DiscordSRVUtils/assets/97077949/e8e3fd03-b6f5-48e7-9bff-30fb4cacc878)
![image](https://github.com/BlueDevelopersInc/DiscordSRVUtils/assets/97077949/526fbc17-ffef-4d86-b365-56871444e828)
![image](https://github.com/BlueDevelopersInc/DiscordSRVUtils/assets/97077949/7a960270-a116-417b-b982-939bd2a0f52f)

**Information:**
Current: git-Purpur-2095 (MC: 1.20.2)
DiscordSRV version 1.27.0
DiscordSRVUtils version 1.2.14-DEV

**Comment by BlueTree242** [comment]
Please test this while your bot has administrator permissions if not already, or you can try giving the bot manage server if it doesn't have (global permission, not on the category)

**Comment by ghost** [comment]
It has admin ![Screenshot_2024-01-24-22-11-15-000_com.discord.jpg](https://github.com/BlueDevelopersInc/DiscordSRVUtils/assets/97077949/bf8a4016-abef-4ebb-bef6-3843e8fa9760)

**Comment by ghost** [comment]
Once again thank you for the fix ❤️
