### ISSUE TITLE
Errors in console when i use /ban,/unban,/tempban

### ISSUE THREAD

**Issue by LevM-A** [BlueTree242/DiscordSRVUtils#16]
Hello, I have an error in my console when I run the / ban / unban / tempban (AdvancedBan) command, etc. then the error in the console gets out and sobsheniya not come to the discord can you help?

https://pastebin.pl/view/4a9d10b7

**Comment by BlueTree242** [comment]
> Hello, I have an error in my console when I run the / ban / unban / tempban (AdvancedBan) command, etc. then the error in the console gets out and sobsheniya not come to the discord can you help?
> 
> https://pastebin.pl/view/4a9d10b7

Pls do /discordsrv debug and send me the link.

**Comment by BlueTree242** [comment]
Your bug has been fixed in [https://www.spigotmc.org/resources/discordsrvutils.85958/update?update=374792](1.0 SNAPSHOT 11)

Delete your old config or add chat_channel option to your config and set it to general (Or whatever in the DiscordSRV config) then reload the plugin.
