### ISSUE TITLE
 Separate channel for bans

### ISSUE THREAD

**Issue by LevM-A** [BlueTree242/DiscordSRVUtils#18]
Is it possible to add a channel selection function for bans, mutes , kicks. If you can do it, I will be very glad THANKS

**Comment by BlueTree242** [comment]
> Is it possible to add a channel selection function for bans, mutes , kicks. If you can do it, I will be very glad THANKS

Yea, but chat might go there

**Comment by LevM-A** [comment]
and if all this is done separately? will there be problems and errors?

**Comment by BlueTree242** [comment]
> and if all this is done separately? will there be problems and errors?

If you followed my steps, no

**Comment by BlueTree242** [comment]
Pls go to discord server so we can talk  https://discord.gg/MMMQHA4

**Comment by LevM-A** [comment]
Okay
