### ISSUE TITLE
DiscordSRV 1.21.0 linking ban check integration

### ISSUE THREAD

**Issue by dmitr-ukhin** [BlueTree242/DiscordSRVUtils#19]
Hello!

In DiscordSRV 1.21.0 update new feature released in linking.yml: "Check banned players" and "Only check banned players".

Now this features works only with vanilla banlist, but I think it would be great to add AdvancedBan and/or other moderation plugin(s) support.

Thank you for a great addon!

**Comment by BlueTree242** [comment]
I am confused, the plugin already supports Advancedban actions goes to discord, if this is not what you want please explain

**Comment by dmitr-ukhin** [comment]
My bad, have not understand DiscordSRV's config explanation correctly, sorry
