### ISSUE TITLE
A new version is available. Please update ASAP! Your version: 1.1.9 New version: 1.1.13 

### ISSUE THREAD

**Issue by Headlessduck406** [BlueTree242/DiscordSRVUtils#44]
Says I have a need a new update, when i just downloaded the latest version 5 minutes ago. The file it self also says it is 1.1.13

**Comment by BlueTree242** [comment]
Ignore, or disable update checker or change the plugin.yml

**Comment by BlueTree242** [comment]
Its like a mistake not issue, wont effect the plugin

**Comment by Headlessduck406** [comment]
ok, thank you

**Comment by CristinaStudios** [comment]
:/

**Comment by BlueTree242** [comment]
Im archiving this plugin soon and releasing a 1000% better one with less bugs and better code

**Comment by Creeperz653** [comment]
YES

**Comment by Creeperz653** [comment]
yes he is
