### ISSUE TITLE
Mohist 1.16.5 Plugin start failed

### ISSUE THREAD

**Issue by Dingroupcr** [BlueTree242/DiscordSRVUtils#85]
![Screenshot_20211117-084448_Samsung Internet](https://user-images.githubusercontent.com/42496449/142094003-b3db63b1-8ce0-4b07-8402-0d9223b18ad8.jpg)
![Screenshot_20211117-084454_Samsung Internet](https://user-images.githubusercontent.com/42496449/142094020-0563fc25-a3fc-4957-b121-d1903ed5e7b7.jpg)
Aternos server sunning total 10 plugins mohist b852 1.16.5 discordsrv 1.24.0 dsu 1.2.3
Server IP 5UP3R_5MP.aternos.me:20293 (not online all time)

**Comment by BlueTree242** [comment]
Mohist not supported, this is why. This error explains the difference between bukkit and mohist from inside. Also why you give me server ip its not like im joining

**Comment by BlueTree242** [comment]
you are also outdated but this does nothing with your problem, i would make a dev build for you but you use aternos

**Comment by BlueTree242** [comment]
Issue not closing because i will work on this soon

**Comment by Dingroupcr** [comment]
> you are also outdated but this does nothing with your problem, i would make a dev build for you but you use aternos

I'm 12 years old and I cant use money without my mom permission yet so I need to use free server host

**Comment by Creeperz653** [comment]
there are tons of free host that allow you to add your own plugins

**Comment by Dingroupcr** [comment]
> there are tons of free host that allow you to add your own plugins

Greay
Then... What is that??

**Comment by BlueTree242** [comment]
I know a very good one but im not telling, since its considered advertising

**Comment by Dingroupcr** [comment]
> I know a very good one but im not telling, since its considered advertising

Just tell me please

**Comment by Dingroupcr** [comment]
> I know a very good one but im not telling, since its considered advertising

Send me in my Discord DM 5UP3R_D1N#3934
Im very need it

**Comment by BlueTree242** [comment]
Sorry but this will not be fixed

**Comment by Dingroupcr** [comment]
Sometime it work
But some feature like command in discord still error
After I installed new skill plugin it just work only 1 time
